#!/bin/bash -x

set -e

function --help {
  echo "Usage: $0 [-n|--dry-run] [-a|-u] [-c COMMAND]"
}

declare -a add_flags

function main {
  while test $# != 0; do
    case $1 in
      -n) shift && dry_run=yes ;;
      -a) shift && add_flags+=(-A) ;;
      -u) shift && add_flags+=(-u) ;;
      -c) shift && command="$1" && shift ;;
      --help) --help && exit 0 ;;
      *) --help && exit 1 ;;
    esac
  done

  test -n "$command" && --run-command "$command"
  --should-add && git add `--add-flags`

  if test -n "$dry_run"; then
    --print-message
  else
    git commit -m "`--print-message`"
  fi
}

function --should-add { --index-clean || test -n "${add_flags[*]}"; }
function --add-flags { echo ${add_flags[*]--u}; }
function --index-clean { test -z "`git diff --cached --shortstat`"; }
function --run-command { (cd "`git rev-parse --show-toplevel`" && $1); }

function --print-message {
  if test -n "$command"; then
    echo "sh -c '$command'"
  else
    stat=`git diff --cached --stat`
    if test `echo "$stat" | wc -l` = 2; then
      symbol=`git diff --cached --name-status | cut -c1`
      echo "`printf %-2s $symbol`" `echo "$stat" | head -1`
    else
      echo "$stat" | tail -1
    fi
  fi
}

main "$@"
