#!/bin/bash

set -e

function working-directory-dirty {
  [[ -n "$(git status --porcelain 2>/dev/null)" ]]
}

function shellquote {
  ruby -r shellwords -e 'puts ARGV.shelljoin' "$@"
}

if [[ $# = 0 ]]; then
  echo Usage: git do COMMAND [ARGS...] && exit 1
elif [[ $# = 1 ]]; then
  command="$1"
else
  if [[ $1 = -f ]]; then
    shift; force=yes
  fi

  command="$(shellquote "$@")"
fi

if [[ $force != yes ]] && working-directory-dirty; then
  echo Your working directory is dirty && exit 1
fi

cd `git rev-parse --show-toplevel`
sh -c "$command"

if working-directory-dirty; then
  git add -A
  git commit -m "\$ $command"
fi
